name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Of 'master', afhankelijk van je branch naam

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace secrets in HTML
        run: |
          sed -i "s|API_KEY_PLACEHOLDER|${{ secrets.FIREBASE_API_KEY }}|g" index.html
          sed -i "s|AUTH_DOMAIN_PLACEHOLDER|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" index.html
          sed -i "s|PROJECT_ID_PLACEHOLDER|${{ secrets.FIREBASE_PROJECT_ID }}|g" index.html
          sed -i "s|STORAGE_BUCKET_PLACEHOLDER|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" index.html
          sed -i "s|SENDER_ID_PLACEHOLDER|${{ secrets.FIREBASE_SENDER_ID }}|g" index.html
          sed -i "s|APP_ID_PLACEHOLDER|${{ secrets.FIREBASE_APP_ID }}|g" index.html
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # De map waar je index.html in staat
          branch: gh-pages # De branch waar de live site op komt te staan
